# -*- coding: utf-8 -*-
from south.utils import datetime_utils as datetime
from south.db import db
from south.v2 import SchemaMigration
from django.db import models


class Migration(SchemaMigration):

    def forwards(self, orm):
        # Adding model 'Precinct'
        db.create_table(u'vm_precinct', (
            ('name', self.gf('django.db.models.fields.CharField')(max_length=255, primary_key=True)),
            ('coord_lat', self.gf('django.db.models.fields.FloatField')(null=True, blank=True)),
            ('coord_lng', self.gf('django.db.models.fields.FloatField')(null=True, blank=True)),
            ('coord_alt', self.gf('django.db.models.fields.FloatField')(null=True, blank=True)),
            ('area', self.gf('django.db.models.fields.FloatField')(null=True, blank=True)),
            ('population', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('count_yes', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('count_no', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('count_undecided', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
            ('count_yardsign', self.gf('django.db.models.fields.IntegerField')(null=True, blank=True)),
        ))
        db.send_create_signal(u'vm', ['Precinct'])

        # Adding model 'Wasco'
        db.create_table(u'Wasco', (
            ('lvoteruniqueid', self.gf('django.db.models.fields.IntegerField')(primary_key=True, db_column=u'lVoterUniqueID')),
            ('saffnumber', self.gf('django.db.models.fields.CharField')(max_length=255, db_column=u'sAffNumber', blank=True)),
            ('szstatevoterid', self.gf('django.db.models.fields.CharField')(max_length=255, db_column=u'szStateVoterID', blank=True)),
            ('svotertitle', self.gf('django.db.models.fields.CharField')(max_length=255, db_column=u'sVoterTitle', blank=True)),
            ('sznamelast', self.gf('django.db.models.fields.CharField')(max_length=255, db_column=u'szNameLast', blank=True)),
            ('sznamefirst', self.gf('django.db.models.fields.CharField')(max_length=255, db_column=u'szNameFirst', blank=True)),
            ('sznamemiddle', self.gf('django.db.models.fields.CharField')(max_length=255, db_column=u'szNameMiddle', blank=True)),
            ('snamesuffix', self.gf('django.db.models.fields.CharField')(max_length=255, db_column=u'sNameSuffix', blank=True)),
            ('sgender', self.gf('django.db.models.fields.CharField')(max_length=255, db_column=u'sGender', blank=True)),
            ('szsitusaddress', self.gf('django.db.models.fields.CharField')(max_length=255, db_column=u'szSitusAddress', blank=True)),
            ('szsituscity', self.gf('django.db.models.fields.CharField')(max_length=255, db_column=u'szSitusCity', blank=True)),
            ('ssitusstate', self.gf('django.db.models.fields.CharField')(max_length=255, db_column=u'sSitusState', blank=True)),
            ('ssituszip', self.gf('django.db.models.fields.CharField')(max_length=255, db_column=u'sSitusZip', blank=True)),
            ('shousenum', self.gf('django.db.models.fields.CharField')(max_length=255, db_column=u'sHouseNum', blank=True)),
            ('sunitabbr', self.gf('django.db.models.fields.CharField')(max_length=255, db_column=u'sUnitAbbr', blank=True)),
            ('sunitnum', self.gf('django.db.models.fields.CharField')(max_length=255, db_column=u'sUnitNum', blank=True)),
            ('szstreetname', self.gf('django.db.models.fields.CharField')(max_length=255, db_column=u'szStreetName', blank=True)),
            ('sstreetsuffix', self.gf('django.db.models.fields.CharField')(max_length=255, db_column=u'sStreetSuffix', blank=True)),
            ('spredir', self.gf('django.db.models.fields.CharField')(max_length=255, db_column=u'sPreDir', blank=True)),
            ('spostdir', self.gf('django.db.models.fields.CharField')(max_length=255, db_column=u'sPostDir', blank=True)),
            ('szmailaddress1', self.gf('django.db.models.fields.CharField')(max_length=255, db_column=u'szMailAddress1', blank=True)),
            ('szmailaddress2', self.gf('django.db.models.fields.CharField')(max_length=255, db_column=u'szMailAddress2', blank=True)),
            ('szmailaddress3', self.gf('django.db.models.fields.CharField')(max_length=255, db_column=u'szMailAddress3', blank=True)),
            ('szmailaddress4', self.gf('django.db.models.fields.CharField')(max_length=255, db_column=u'szMailAddress4', blank=True)),
            ('szmailzip', self.gf('django.db.models.fields.CharField')(max_length=255, db_column=u'szMailZip', blank=True)),
            ('szphone', self.gf('django.db.models.fields.CharField')(max_length=255, db_column=u'szPhone', blank=True)),
            ('szemailaddress', self.gf('django.db.models.fields.CharField')(max_length=255, db_column=u'szEmailAddress', blank=True)),
            ('dtbirthdate', self.gf('django.db.models.fields.CharField')(max_length=255, db_column=u'dtBirthDate', blank=True)),
            ('sbirthplace', self.gf('django.db.models.fields.CharField')(max_length=255, db_column=u'sBirthPlace', blank=True)),
            ('dtregdate', self.gf('django.db.models.fields.CharField')(max_length=255, db_column=u'dtRegDate', blank=True)),
            ('dtorigregdate', self.gf('django.db.models.fields.CharField')(max_length=255, db_column=u'dtOrigRegDate', blank=True)),
            ('dtlastupdate_dt', self.gf('django.db.models.fields.CharField')(max_length=255, db_column=u'dtLastUpdate_dt', blank=True)),
            ('sstatuscode', self.gf('django.db.models.fields.CharField')(max_length=255, db_column=u'sStatusCode', blank=True)),
            ('szstatusreasondesc', self.gf('django.db.models.fields.CharField')(max_length=255, db_column=u'szStatusReasonDesc', blank=True)),
            ('susercode1', self.gf('django.db.models.fields.CharField')(max_length=255, db_column=u'sUserCode1', blank=True)),
            ('susercode2', self.gf('django.db.models.fields.CharField')(max_length=255, db_column=u'sUserCode2', blank=True)),
            ('iduplicateidflag', self.gf('django.db.models.fields.CharField')(max_length=255, db_column=u'iDuplicateIDFlag', blank=True)),
            ('szlanguagename', self.gf('django.db.models.fields.CharField')(max_length=255, db_column=u'szLanguageName', blank=True)),
            ('szpartyname', self.gf('django.db.models.fields.CharField')(max_length=255, db_column=u'szPartyName', blank=True)),
            ('szavstatusabbr', self.gf('django.db.models.fields.CharField')(max_length=255, db_column=u'szAVStatusAbbr', blank=True)),
            ('szavstatusdesc', self.gf('django.db.models.fields.CharField')(max_length=255, db_column=u'szAVStatusDesc', blank=True)),
            ('szprecinctname', self.gf('django.db.models.fields.CharField')(max_length=255, db_column=u'szPrecinctName', blank=True)),
            ('sprecinctid', self.gf('django.db.models.fields.CharField')(max_length=255, db_column=u'sPrecinctID', blank=True)),
            ('sprecinctportion', self.gf('django.db.models.fields.CharField')(max_length=255, db_column=u'sPrecinctPortion', blank=True)),
            ('sdistrictid_0', self.gf('django.db.models.fields.CharField')(max_length=255, db_column=u'sDistrictID_0', blank=True)),
            ('isubdistrict_0', self.gf('django.db.models.fields.CharField')(max_length=255, db_column=u'iSubDistrict_0', blank=True)),
            ('szdistrictname_0', self.gf('django.db.models.fields.CharField')(max_length=255, db_column=u'szDistrictName_0', blank=True)),
            ('sdistrictid_1', self.gf('django.db.models.fields.CharField')(max_length=255, db_column=u'sDistrictID_1', blank=True)),
            ('isubdistrict_1', self.gf('django.db.models.fields.CharField')(max_length=255, db_column=u'iSubDistrict_1', blank=True)),
            ('szdistrictname_1', self.gf('django.db.models.fields.CharField')(max_length=255, db_column=u'szDistrictName_1', blank=True)),
            ('sdistrictid_2', self.gf('django.db.models.fields.CharField')(max_length=255, db_column=u'sDistrictID_2', blank=True)),
            ('isubdistrict_2', self.gf('django.db.models.fields.CharField')(max_length=255, db_column=u'iSubDistrict_2', blank=True)),
            ('szdistrictname_2', self.gf('django.db.models.fields.CharField')(max_length=255, db_column=u'szDistrictName_2', blank=True)),
            ('sdistrictid_3', self.gf('django.db.models.fields.CharField')(max_length=255, db_column=u'sDistrictID_3', blank=True)),
            ('isubdistrict_3', self.gf('django.db.models.fields.CharField')(max_length=255, db_column=u'iSubDistrict_3', blank=True)),
            ('szdistrictname_3', self.gf('django.db.models.fields.CharField')(max_length=255, db_column=u'szDistrictName_3', blank=True)),
            ('sdistrictid_4', self.gf('django.db.models.fields.CharField')(max_length=255, db_column=u'sDistrictID_4', blank=True)),
            ('isubdistrict_4', self.gf('django.db.models.fields.CharField')(max_length=255, db_column=u'iSubDistrict_4', blank=True)),
            ('szdistrictname_4', self.gf('django.db.models.fields.CharField')(max_length=255, db_column=u'szDistrictName_4', blank=True)),
            ('sdistrictid_5', self.gf('django.db.models.fields.CharField')(max_length=255, db_column=u'sDistrictID_5', blank=True)),
            ('isubdistrict_5', self.gf('django.db.models.fields.CharField')(max_length=255, db_column=u'iSubDistrict_5', blank=True)),
            ('szdistrictname_5', self.gf('django.db.models.fields.CharField')(max_length=255, db_column=u'szDistrictName_5', blank=True)),
            ('selectionabbr1', self.gf('django.db.models.fields.CharField')(max_length=255, db_column=u'sElectionAbbr1', blank=True)),
            ('szelectiondesc1', self.gf('django.db.models.fields.CharField')(max_length=255, db_column=u'szElectionDesc1', blank=True)),
            ('dtelectiondate1', self.gf('django.db.models.fields.CharField')(max_length=255, db_column=u'dtElectionDate1', blank=True)),
            ('selectypedesc1', self.gf('django.db.models.fields.CharField')(max_length=255, db_column=u'sElecTypeDesc1', blank=True)),
            ('svotingprecinct1', self.gf('django.db.models.fields.CharField')(max_length=255, db_column=u'sVotingPrecinct1', blank=True)),
            ('szvotingmethod1', self.gf('django.db.models.fields.CharField')(max_length=255, db_column=u'szVotingMethod1', blank=True)),
            ('spartyabbr1', self.gf('django.db.models.fields.CharField')(max_length=255, db_column=u'sPartyAbbr1', blank=True)),
            ('szpartyname1', self.gf('django.db.models.fields.CharField')(max_length=255, db_column=u'szPartyName1', blank=True)),
            ('szcountedflag1', self.gf('django.db.models.fields.CharField')(max_length=255, db_column=u'szCountedFlag1', blank=True)),
            ('selectionabbr2', self.gf('django.db.models.fields.CharField')(max_length=255, db_column=u'sElectionAbbr2', blank=True)),
            ('szelectiondesc2', self.gf('django.db.models.fields.CharField')(max_length=255, db_column=u'szElectionDesc2', blank=True)),
            ('dtelectiondate2', self.gf('django.db.models.fields.CharField')(max_length=255, db_column=u'dtElectionDate2', blank=True)),
            ('selectypedesc2', self.gf('django.db.models.fields.CharField')(max_length=255, db_column=u'sElecTypeDesc2', blank=True)),
            ('svotingprecinct2', self.gf('django.db.models.fields.CharField')(max_length=255, db_column=u'sVotingPrecinct2', blank=True)),
            ('szvotingmethod2', self.gf('django.db.models.fields.CharField')(max_length=255, db_column=u'szVotingMethod2', blank=True)),
            ('spartyabbr2', self.gf('django.db.models.fields.CharField')(max_length=255, db_column=u'sPartyAbbr2', blank=True)),
            ('szpartyname2', self.gf('django.db.models.fields.CharField')(max_length=255, db_column=u'szPartyName2', blank=True)),
            ('szcountedflag2', self.gf('django.db.models.fields.CharField')(max_length=255, db_column=u'szCountedFlag2', blank=True)),
            ('selectionabbr3', self.gf('django.db.models.fields.CharField')(max_length=255, db_column=u'sElectionAbbr3', blank=True)),
            ('szelectiondesc3', self.gf('django.db.models.fields.CharField')(max_length=255, db_column=u'szElectionDesc3', blank=True)),
            ('dtelectiondate3', self.gf('django.db.models.fields.CharField')(max_length=255, db_column=u'dtElectionDate3', blank=True)),
            ('selectypedesc3', self.gf('django.db.models.fields.CharField')(max_length=255, db_column=u'sElecTypeDesc3', blank=True)),
            ('svotingprecinct3', self.gf('django.db.models.fields.CharField')(max_length=255, db_column=u'sVotingPrecinct3', blank=True)),
            ('szvotingmethod3', self.gf('django.db.models.fields.CharField')(max_length=255, db_column=u'szVotingMethod3', blank=True)),
            ('spartyabbr3', self.gf('django.db.models.fields.CharField')(max_length=255, db_column=u'sPartyAbbr3', blank=True)),
            ('szpartyname3', self.gf('django.db.models.fields.CharField')(max_length=255, db_column=u'szPartyName3', blank=True)),
            ('szcountedflag3', self.gf('django.db.models.fields.CharField')(max_length=255, db_column=u'szCountedFlag3', blank=True)),
            ('selectionabbr4', self.gf('django.db.models.fields.CharField')(max_length=255, db_column=u'sElectionAbbr4', blank=True)),
            ('szelectiondesc4', self.gf('django.db.models.fields.CharField')(max_length=255, db_column=u'szElectionDesc4', blank=True)),
            ('dtelectiondate4', self.gf('django.db.models.fields.CharField')(max_length=255, db_column=u'dtElectionDate4', blank=True)),
            ('selectypedesc4', self.gf('django.db.models.fields.CharField')(max_length=255, db_column=u'sElecTypeDesc4', blank=True)),
            ('svotingprecinct4', self.gf('django.db.models.fields.CharField')(max_length=255, db_column=u'sVotingPrecinct4', blank=True)),
            ('szvotingmethod4', self.gf('django.db.models.fields.CharField')(max_length=255, db_column=u'szVotingMethod4', blank=True)),
            ('spartyabbr4', self.gf('django.db.models.fields.CharField')(max_length=255, db_column=u'sPartyAbbr4', blank=True)),
            ('szpartyname4', self.gf('django.db.models.fields.CharField')(max_length=255, db_column=u'szPartyName4', blank=True)),
            ('szcountedflag4', self.gf('django.db.models.fields.CharField')(max_length=255, db_column=u'szCountedFlag4', blank=True)),
            ('selectionabbr5', self.gf('django.db.models.fields.CharField')(max_length=255, db_column=u'sElectionAbbr5', blank=True)),
            ('szelectiondesc5', self.gf('django.db.models.fields.CharField')(max_length=255, db_column=u'szElectionDesc5', blank=True)),
            ('dtelectiondate5', self.gf('django.db.models.fields.CharField')(max_length=255, db_column=u'dtElectionDate5', blank=True)),
            ('selectypedesc5', self.gf('django.db.models.fields.CharField')(max_length=255, db_column=u'sElecTypeDesc5', blank=True)),
            ('svotingprecinct5', self.gf('django.db.models.fields.CharField')(max_length=255, db_column=u'sVotingPrecinct5', blank=True)),
            ('szvotingmethod5', self.gf('django.db.models.fields.CharField')(max_length=255, db_column=u'szVotingMethod5', blank=True)),
            ('spartyabbr5', self.gf('django.db.models.fields.CharField')(max_length=255, db_column=u'sPartyAbbr5', blank=True)),
            ('szpartyname5', self.gf('django.db.models.fields.CharField')(max_length=255, db_column=u'szPartyName5', blank=True)),
            ('szcountedflag5', self.gf('django.db.models.fields.CharField')(max_length=255, db_column=u'szCountedFlag5', blank=True)),
            ('voter_response', self.gf('django.db.models.fields.IntegerField')(null=True)),
            ('yardsign', self.gf('django.db.models.fields.NullBooleanField')(null=True, blank=True)),
            ('time_response', self.gf('django.db.models.fields.DateTimeField')(default=datetime.datetime.now, blank=True)),
        ))
        db.send_create_signal(u'vm', ['Wasco'])


    def backwards(self, orm):
        # Deleting model 'Precinct'
        db.delete_table(u'vm_precinct')

        # Deleting model 'Wasco'
        db.delete_table(u'Wasco')


    models = {
        u'vm.precinct': {
            'Meta': {'object_name': 'Precinct'},
            'area': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'coord_alt': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'coord_lat': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'coord_lng': ('django.db.models.fields.FloatField', [], {'null': 'True', 'blank': 'True'}),
            'count_no': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'count_undecided': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'count_yardsign': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'count_yes': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'}),
            'name': ('django.db.models.fields.CharField', [], {'max_length': '255', 'primary_key': 'True'}),
            'population': ('django.db.models.fields.IntegerField', [], {'null': 'True', 'blank': 'True'})
        },
        u'vm.wasco': {
            'Meta': {'object_name': 'Wasco', 'db_table': "u'Wasco'"},
            'dtbirthdate': ('django.db.models.fields.CharField', [], {'max_length': '255', 'db_column': "u'dtBirthDate'", 'blank': 'True'}),
            'dtelectiondate1': ('django.db.models.fields.CharField', [], {'max_length': '255', 'db_column': "u'dtElectionDate1'", 'blank': 'True'}),
            'dtelectiondate2': ('django.db.models.fields.CharField', [], {'max_length': '255', 'db_column': "u'dtElectionDate2'", 'blank': 'True'}),
            'dtelectiondate3': ('django.db.models.fields.CharField', [], {'max_length': '255', 'db_column': "u'dtElectionDate3'", 'blank': 'True'}),
            'dtelectiondate4': ('django.db.models.fields.CharField', [], {'max_length': '255', 'db_column': "u'dtElectionDate4'", 'blank': 'True'}),
            'dtelectiondate5': ('django.db.models.fields.CharField', [], {'max_length': '255', 'db_column': "u'dtElectionDate5'", 'blank': 'True'}),
            'dtlastupdate_dt': ('django.db.models.fields.CharField', [], {'max_length': '255', 'db_column': "u'dtLastUpdate_dt'", 'blank': 'True'}),
            'dtorigregdate': ('django.db.models.fields.CharField', [], {'max_length': '255', 'db_column': "u'dtOrigRegDate'", 'blank': 'True'}),
            'dtregdate': ('django.db.models.fields.CharField', [], {'max_length': '255', 'db_column': "u'dtRegDate'", 'blank': 'True'}),
            'iduplicateidflag': ('django.db.models.fields.CharField', [], {'max_length': '255', 'db_column': "u'iDuplicateIDFlag'", 'blank': 'True'}),
            'isubdistrict_0': ('django.db.models.fields.CharField', [], {'max_length': '255', 'db_column': "u'iSubDistrict_0'", 'blank': 'True'}),
            'isubdistrict_1': ('django.db.models.fields.CharField', [], {'max_length': '255', 'db_column': "u'iSubDistrict_1'", 'blank': 'True'}),
            'isubdistrict_2': ('django.db.models.fields.CharField', [], {'max_length': '255', 'db_column': "u'iSubDistrict_2'", 'blank': 'True'}),
            'isubdistrict_3': ('django.db.models.fields.CharField', [], {'max_length': '255', 'db_column': "u'iSubDistrict_3'", 'blank': 'True'}),
            'isubdistrict_4': ('django.db.models.fields.CharField', [], {'max_length': '255', 'db_column': "u'iSubDistrict_4'", 'blank': 'True'}),
            'isubdistrict_5': ('django.db.models.fields.CharField', [], {'max_length': '255', 'db_column': "u'iSubDistrict_5'", 'blank': 'True'}),
            'lvoteruniqueid': ('django.db.models.fields.IntegerField', [], {'primary_key': 'True', 'db_column': "u'lVoterUniqueID'"}),
            'saffnumber': ('django.db.models.fields.CharField', [], {'max_length': '255', 'db_column': "u'sAffNumber'", 'blank': 'True'}),
            'sbirthplace': ('django.db.models.fields.CharField', [], {'max_length': '255', 'db_column': "u'sBirthPlace'", 'blank': 'True'}),
            'sdistrictid_0': ('django.db.models.fields.CharField', [], {'max_length': '255', 'db_column': "u'sDistrictID_0'", 'blank': 'True'}),
            'sdistrictid_1': ('django.db.models.fields.CharField', [], {'max_length': '255', 'db_column': "u'sDistrictID_1'", 'blank': 'True'}),
            'sdistrictid_2': ('django.db.models.fields.CharField', [], {'max_length': '255', 'db_column': "u'sDistrictID_2'", 'blank': 'True'}),
            'sdistrictid_3': ('django.db.models.fields.CharField', [], {'max_length': '255', 'db_column': "u'sDistrictID_3'", 'blank': 'True'}),
            'sdistrictid_4': ('django.db.models.fields.CharField', [], {'max_length': '255', 'db_column': "u'sDistrictID_4'", 'blank': 'True'}),
            'sdistrictid_5': ('django.db.models.fields.CharField', [], {'max_length': '255', 'db_column': "u'sDistrictID_5'", 'blank': 'True'}),
            'selectionabbr1': ('django.db.models.fields.CharField', [], {'max_length': '255', 'db_column': "u'sElectionAbbr1'", 'blank': 'True'}),
            'selectionabbr2': ('django.db.models.fields.CharField', [], {'max_length': '255', 'db_column': "u'sElectionAbbr2'", 'blank': 'True'}),
            'selectionabbr3': ('django.db.models.fields.CharField', [], {'max_length': '255', 'db_column': "u'sElectionAbbr3'", 'blank': 'True'}),
            'selectionabbr4': ('django.db.models.fields.CharField', [], {'max_length': '255', 'db_column': "u'sElectionAbbr4'", 'blank': 'True'}),
            'selectionabbr5': ('django.db.models.fields.CharField', [], {'max_length': '255', 'db_column': "u'sElectionAbbr5'", 'blank': 'True'}),
            'selectypedesc1': ('django.db.models.fields.CharField', [], {'max_length': '255', 'db_column': "u'sElecTypeDesc1'", 'blank': 'True'}),
            'selectypedesc2': ('django.db.models.fields.CharField', [], {'max_length': '255', 'db_column': "u'sElecTypeDesc2'", 'blank': 'True'}),
            'selectypedesc3': ('django.db.models.fields.CharField', [], {'max_length': '255', 'db_column': "u'sElecTypeDesc3'", 'blank': 'True'}),
            'selectypedesc4': ('django.db.models.fields.CharField', [], {'max_length': '255', 'db_column': "u'sElecTypeDesc4'", 'blank': 'True'}),
            'selectypedesc5': ('django.db.models.fields.CharField', [], {'max_length': '255', 'db_column': "u'sElecTypeDesc5'", 'blank': 'True'}),
            'sgender': ('django.db.models.fields.CharField', [], {'max_length': '255', 'db_column': "u'sGender'", 'blank': 'True'}),
            'shousenum': ('django.db.models.fields.CharField', [], {'max_length': '255', 'db_column': "u'sHouseNum'", 'blank': 'True'}),
            'snamesuffix': ('django.db.models.fields.CharField', [], {'max_length': '255', 'db_column': "u'sNameSuffix'", 'blank': 'True'}),
            'spartyabbr1': ('django.db.models.fields.CharField', [], {'max_length': '255', 'db_column': "u'sPartyAbbr1'", 'blank': 'True'}),
            'spartyabbr2': ('django.db.models.fields.CharField', [], {'max_length': '255', 'db_column': "u'sPartyAbbr2'", 'blank': 'True'}),
            'spartyabbr3': ('django.db.models.fields.CharField', [], {'max_length': '255', 'db_column': "u'sPartyAbbr3'", 'blank': 'True'}),
            'spartyabbr4': ('django.db.models.fields.CharField', [], {'max_length': '255', 'db_column': "u'sPartyAbbr4'", 'blank': 'True'}),
            'spartyabbr5': ('django.db.models.fields.CharField', [], {'max_length': '255', 'db_column': "u'sPartyAbbr5'", 'blank': 'True'}),
            'spostdir': ('django.db.models.fields.CharField', [], {'max_length': '255', 'db_column': "u'sPostDir'", 'blank': 'True'}),
            'sprecinctid': ('django.db.models.fields.CharField', [], {'max_length': '255', 'db_column': "u'sPrecinctID'", 'blank': 'True'}),
            'sprecinctportion': ('django.db.models.fields.CharField', [], {'max_length': '255', 'db_column': "u'sPrecinctPortion'", 'blank': 'True'}),
            'spredir': ('django.db.models.fields.CharField', [], {'max_length': '255', 'db_column': "u'sPreDir'", 'blank': 'True'}),
            'ssitusstate': ('django.db.models.fields.CharField', [], {'max_length': '255', 'db_column': "u'sSitusState'", 'blank': 'True'}),
            'ssituszip': ('django.db.models.fields.CharField', [], {'max_length': '255', 'db_column': "u'sSitusZip'", 'blank': 'True'}),
            'sstatuscode': ('django.db.models.fields.CharField', [], {'max_length': '255', 'db_column': "u'sStatusCode'", 'blank': 'True'}),
            'sstreetsuffix': ('django.db.models.fields.CharField', [], {'max_length': '255', 'db_column': "u'sStreetSuffix'", 'blank': 'True'}),
            'sunitabbr': ('django.db.models.fields.CharField', [], {'max_length': '255', 'db_column': "u'sUnitAbbr'", 'blank': 'True'}),
            'sunitnum': ('django.db.models.fields.CharField', [], {'max_length': '255', 'db_column': "u'sUnitNum'", 'blank': 'True'}),
            'susercode1': ('django.db.models.fields.CharField', [], {'max_length': '255', 'db_column': "u'sUserCode1'", 'blank': 'True'}),
            'susercode2': ('django.db.models.fields.CharField', [], {'max_length': '255', 'db_column': "u'sUserCode2'", 'blank': 'True'}),
            'svotertitle': ('django.db.models.fields.CharField', [], {'max_length': '255', 'db_column': "u'sVoterTitle'", 'blank': 'True'}),
            'svotingprecinct1': ('django.db.models.fields.CharField', [], {'max_length': '255', 'db_column': "u'sVotingPrecinct1'", 'blank': 'True'}),
            'svotingprecinct2': ('django.db.models.fields.CharField', [], {'max_length': '255', 'db_column': "u'sVotingPrecinct2'", 'blank': 'True'}),
            'svotingprecinct3': ('django.db.models.fields.CharField', [], {'max_length': '255', 'db_column': "u'sVotingPrecinct3'", 'blank': 'True'}),
            'svotingprecinct4': ('django.db.models.fields.CharField', [], {'max_length': '255', 'db_column': "u'sVotingPrecinct4'", 'blank': 'True'}),
            'svotingprecinct5': ('django.db.models.fields.CharField', [], {'max_length': '255', 'db_column': "u'sVotingPrecinct5'", 'blank': 'True'}),
            'szavstatusabbr': ('django.db.models.fields.CharField', [], {'max_length': '255', 'db_column': "u'szAVStatusAbbr'", 'blank': 'True'}),
            'szavstatusdesc': ('django.db.models.fields.CharField', [], {'max_length': '255', 'db_column': "u'szAVStatusDesc'", 'blank': 'True'}),
            'szcountedflag1': ('django.db.models.fields.CharField', [], {'max_length': '255', 'db_column': "u'szCountedFlag1'", 'blank': 'True'}),
            'szcountedflag2': ('django.db.models.fields.CharField', [], {'max_length': '255', 'db_column': "u'szCountedFlag2'", 'blank': 'True'}),
            'szcountedflag3': ('django.db.models.fields.CharField', [], {'max_length': '255', 'db_column': "u'szCountedFlag3'", 'blank': 'True'}),
            'szcountedflag4': ('django.db.models.fields.CharField', [], {'max_length': '255', 'db_column': "u'szCountedFlag4'", 'blank': 'True'}),
            'szcountedflag5': ('django.db.models.fields.CharField', [], {'max_length': '255', 'db_column': "u'szCountedFlag5'", 'blank': 'True'}),
            'szdistrictname_0': ('django.db.models.fields.CharField', [], {'max_length': '255', 'db_column': "u'szDistrictName_0'", 'blank': 'True'}),
            'szdistrictname_1': ('django.db.models.fields.CharField', [], {'max_length': '255', 'db_column': "u'szDistrictName_1'", 'blank': 'True'}),
            'szdistrictname_2': ('django.db.models.fields.CharField', [], {'max_length': '255', 'db_column': "u'szDistrictName_2'", 'blank': 'True'}),
            'szdistrictname_3': ('django.db.models.fields.CharField', [], {'max_length': '255', 'db_column': "u'szDistrictName_3'", 'blank': 'True'}),
            'szdistrictname_4': ('django.db.models.fields.CharField', [], {'max_length': '255', 'db_column': "u'szDistrictName_4'", 'blank': 'True'}),
            'szdistrictname_5': ('django.db.models.fields.CharField', [], {'max_length': '255', 'db_column': "u'szDistrictName_5'", 'blank': 'True'}),
            'szelectiondesc1': ('django.db.models.fields.CharField', [], {'max_length': '255', 'db_column': "u'szElectionDesc1'", 'blank': 'True'}),
            'szelectiondesc2': ('django.db.models.fields.CharField', [], {'max_length': '255', 'db_column': "u'szElectionDesc2'", 'blank': 'True'}),
            'szelectiondesc3': ('django.db.models.fields.CharField', [], {'max_length': '255', 'db_column': "u'szElectionDesc3'", 'blank': 'True'}),
            'szelectiondesc4': ('django.db.models.fields.CharField', [], {'max_length': '255', 'db_column': "u'szElectionDesc4'", 'blank': 'True'}),
            'szelectiondesc5': ('django.db.models.fields.CharField', [], {'max_length': '255', 'db_column': "u'szElectionDesc5'", 'blank': 'True'}),
            'szemailaddress': ('django.db.models.fields.CharField', [], {'max_length': '255', 'db_column': "u'szEmailAddress'", 'blank': 'True'}),
            'szlanguagename': ('django.db.models.fields.CharField', [], {'max_length': '255', 'db_column': "u'szLanguageName'", 'blank': 'True'}),
            'szmailaddress1': ('django.db.models.fields.CharField', [], {'max_length': '255', 'db_column': "u'szMailAddress1'", 'blank': 'True'}),
            'szmailaddress2': ('django.db.models.fields.CharField', [], {'max_length': '255', 'db_column': "u'szMailAddress2'", 'blank': 'True'}),
            'szmailaddress3': ('django.db.models.fields.CharField', [], {'max_length': '255', 'db_column': "u'szMailAddress3'", 'blank': 'True'}),
            'szmailaddress4': ('django.db.models.fields.CharField', [], {'max_length': '255', 'db_column': "u'szMailAddress4'", 'blank': 'True'}),
            'szmailzip': ('django.db.models.fields.CharField', [], {'max_length': '255', 'db_column': "u'szMailZip'", 'blank': 'True'}),
            'sznamefirst': ('django.db.models.fields.CharField', [], {'max_length': '255', 'db_column': "u'szNameFirst'", 'blank': 'True'}),
            'sznamelast': ('django.db.models.fields.CharField', [], {'max_length': '255', 'db_column': "u'szNameLast'", 'blank': 'True'}),
            'sznamemiddle': ('django.db.models.fields.CharField', [], {'max_length': '255', 'db_column': "u'szNameMiddle'", 'blank': 'True'}),
            'szpartyname': ('django.db.models.fields.CharField', [], {'max_length': '255', 'db_column': "u'szPartyName'", 'blank': 'True'}),
            'szpartyname1': ('django.db.models.fields.CharField', [], {'max_length': '255', 'db_column': "u'szPartyName1'", 'blank': 'True'}),
            'szpartyname2': ('django.db.models.fields.CharField', [], {'max_length': '255', 'db_column': "u'szPartyName2'", 'blank': 'True'}),
            'szpartyname3': ('django.db.models.fields.CharField', [], {'max_length': '255', 'db_column': "u'szPartyName3'", 'blank': 'True'}),
            'szpartyname4': ('django.db.models.fields.CharField', [], {'max_length': '255', 'db_column': "u'szPartyName4'", 'blank': 'True'}),
            'szpartyname5': ('django.db.models.fields.CharField', [], {'max_length': '255', 'db_column': "u'szPartyName5'", 'blank': 'True'}),
            'szphone': ('django.db.models.fields.CharField', [], {'max_length': '255', 'db_column': "u'szPhone'", 'blank': 'True'}),
            'szprecinctname': ('django.db.models.fields.CharField', [], {'max_length': '255', 'db_column': "u'szPrecinctName'", 'blank': 'True'}),
            'szsitusaddress': ('django.db.models.fields.CharField', [], {'max_length': '255', 'db_column': "u'szSitusAddress'", 'blank': 'True'}),
            'szsituscity': ('django.db.models.fields.CharField', [], {'max_length': '255', 'db_column': "u'szSitusCity'", 'blank': 'True'}),
            'szstatevoterid': ('django.db.models.fields.CharField', [], {'max_length': '255', 'db_column': "u'szStateVoterID'", 'blank': 'True'}),
            'szstatusreasondesc': ('django.db.models.fields.CharField', [], {'max_length': '255', 'db_column': "u'szStatusReasonDesc'", 'blank': 'True'}),
            'szstreetname': ('django.db.models.fields.CharField', [], {'max_length': '255', 'db_column': "u'szStreetName'", 'blank': 'True'}),
            'szvotingmethod1': ('django.db.models.fields.CharField', [], {'max_length': '255', 'db_column': "u'szVotingMethod1'", 'blank': 'True'}),
            'szvotingmethod2': ('django.db.models.fields.CharField', [], {'max_length': '255', 'db_column': "u'szVotingMethod2'", 'blank': 'True'}),
            'szvotingmethod3': ('django.db.models.fields.CharField', [], {'max_length': '255', 'db_column': "u'szVotingMethod3'", 'blank': 'True'}),
            'szvotingmethod4': ('django.db.models.fields.CharField', [], {'max_length': '255', 'db_column': "u'szVotingMethod4'", 'blank': 'True'}),
            'szvotingmethod5': ('django.db.models.fields.CharField', [], {'max_length': '255', 'db_column': "u'szVotingMethod5'", 'blank': 'True'}),
            'time_response': ('django.db.models.fields.DateTimeField', [], {'default': 'datetime.datetime.now', 'blank': 'True'}),
            'voter_response': ('django.db.models.fields.IntegerField', [], {'null': 'True'}),
            'yardsign': ('django.db.models.fields.NullBooleanField', [], {'null': 'True', 'blank': 'True'})
        }
    }

    complete_apps = ['vm']